test

diff --git a/.github/workflows/php-syntax-check.yml b/.github/workflows/php-syntax-check.yml
--- a/.github/workflows/php-syntax-check.yml
+++ b/.github/workflows/php-syntax-check.yml
@@ -19,14 +19,28 @@ jobs:
       - name: Set up PHP
         uses: shivammathur/setup-php@v2
         with:
-          php-version: '7.2' # 指定所需的PHP版本，比如 7.4, 8.0, 或 8.1 等
+          php-version: '7.2' # 指定所需的PHP版本
 
-      - name: Validate PHP files
+      - name: Check syntax for changed PHP files
         run: |
-          ERR=0
-          for file in $(find . -type f -name "*.php"); do
-          php -l $file || ERR=1
-          done
-          if [ "$ERR" == "1" ]; then
-          exit 1
+          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$')
+          if [ -z "$CHANGED_FILES" ]; then
+            echo "No PHP files to check"
+            exit 0
           fi
+          # 遍历所有更改的.php文件并检查语法
+          echo "Checking PHP syntax..."
+          ERROR=0
+          for FILE in $CHANGED_FILES; do
+            echo "Syntax checking $FILE"
+            php -l $FILE
+            if [ $? -ne 0 ]; then
+              echo "Syntax error detected in $FILE"
+              ERROR=1
+            fi
+          done
+          # 如果发现语法错误则退出
+          if [ $ERROR -ne 0 ]; then
+            exit 1
+          fi
+          echo "No syntax errors detected"
