test4

diff --git a/.github/workflows/php-syntax-check.yml b/.github/workflows/php-syntax-check.yml
--- a/.github/workflows/php-syntax-check.yml
+++ b/.github/workflows/php-syntax-check.yml
@@ -37,16 +37,19 @@ jobs:
             echo "No PHP files to check"
             exit 0
           fi
+          ERR=0
           for FILE in $CHANGED_FILES; do
             if [ -f "$FILE" ]; then
               echo "Syntax checking in $FILE"
               php -l "$FILE"
               if [ $? -ne 0 ]; then
                 echo "Syntax error detected in $FILE"
-                exit 1
+                ERR=1
               fi
-            else
-              echo "'$FILE' cannot be found or is not a valid file."
-            fi
           done
+          if [ "$ERR" == "1" ]; then
+            exit 1
+          else
+            echo "success, cannot be found or is not a valid file"
+          fi
 
